AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyUser:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
      Policies: 
        - PolicyName: MyCoolPolicy
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Sid: IamListAccess
                Effect: Allow
                Action:
                  - 'iam:ListRoles'
                  - 'iam:ListUsers'
                Resource: '*'

  MyInlinePolicy:
    Type: 'AWS::IAM::UserPolicy'
    Properties:
      PolicyName: MyInlinePolicy
      UserName: !Ref MyUser  # Corrected from 'Users'
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 'ec2:*'
            Resource: '*'

  MySecondInlinePolicy: 
    Type: 'AWS::IAM::UserPolicy'
    Properties:
      PolicyName: MySecondInlinePolicy
      UserName: !Ref MyUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 's3:*'
            Resource: '*'
