#!/usr/bin/env bash
echo "== list bucket"

aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[] | .Name'

#Use this below command when you want to see the output in jSON format 
#since while configuring aws I have set the output default to Table
#aws s3api list-buckets --output json | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[] | .Name'



